---
- hosts: docker
  become: true
  roles:
    - disable-selinux
    - add-hosts
    - firewall-http
    - firewall-nrpe
    - git
    - { role: geerlingguy.java,when: "ansible_os_family == 'RedHat'", java_packages: java-11-openjdk }
    - geerlingguy.docker
    - nrpe
    - dob-network
